### ISSUE TITLE
The method save(S) in the type CrudRepository<SecondaryModel,String> is not applicable for the arguments (SecondaryModel)

### ISSUE THREAD

**Issue by ToJen** [weekly-drafts/spring-boot-multi-mongo#1]
There seems to be an issue with `Application.java` on the following lines

```java
  this.primaryRepository.save(new PrimaryModel(null, "Primary database plain object"));
  this.secondaryRepository.save(new SecondaryModel(null, "Secondary database plain object"));
```

**Comment by marcosbarbero** [comment]
Hi @ToJen sorry for the delay and thanks for the heads up, I'll do my best to look into it tomorrow.

**Comment by ToJen** [comment]
I ended up creating an endpoint on a different backend that controls the secondary db as an alternative approach.
